### ISSUE TITLE
Board größe

### ISSUE THREAD

**Issue by codebro634** [informatiCup/InformatiCup2021#10]
bleibt die board größe immer gleich? Oder müssen wir einen agenten entwickeln der auf spielfeldern beliebiger größe spielen kann?

**Comment by Top-Ranger** [comment]
Die (variable) Größe des Spielfeldes wird für jedes Spiel im JSON mitgegeben und ändert sich während eines Spieles nicht.

**Comment by epistoteles** [comment]
Gibt es eine Maximalgrösse? Insbesondere bei großen Spielbrettern steigt nicht nur die Anzahl der Felder quadratisch, sondern damit auch die durchschnittliche Spieldauer erheblich. Eine Limitierung wäre hier hilfreich.

**Comment by Top-Ranger** [comment]
Die Aufgabenbeschreibung macht keine weiteren Angaben zur Spielfeldgröße.

**Comment by Top-Ranger** [comment]
Als Ergänzung: Während eines Spieles ändert sich die Größe des Spielfelds nicht
