### ISSUE TITLE
Specs der Referenzsysteme

### ISSUE THREAD

**Issue by mzietlow** [informatiCup/InformatiCup2021#11]
Können die Specs der Referenzsysteme, e.g. RAM, CPU, GPU~VRAM, veröffentlicht werden?

**Comment by Top-Ranger** [comment]
Sie können davon ausgehen, dass es sich um moderne Mehrkernprozessor-Computer mit einigen GB RAM und keiner speziellen
Grafikkarte handelt. Es ist möglich, dass die Systeme virtualisiert sind.
