### ISSUE TITLE
Was passiert mit zwei Schlangen, die sich gleichzeitig kreuzen?

### ISSUE THREAD

**Issue by codebro634** [informatiCup/InformatiCup2021#13]
Angenommen wir haben zwei Schlangen s1, s2 an den Positionen (x1,y1) = (0,1) in Richtung Rechts mit Geschwindigkeit 2 und
(x2,y2) = (1,2) in Richtung Oben mit Geschwindigkeit 2.  Nach dem Zug wären die neuen Positionen dann (x1,y1) = (2,1) und (x2,y2) = (1,0). Die Schlangen hätten sich an (1,1) gekreuzt. Leben beide Schlangen noch oder sind beide tot?

**Comment by pa-ssch** [comment]
[siehe Issue5](https://github.com/informatiCup/InformatiCup2021/issues/5)

**Comment by codebro634** [comment]
Ah das hab ich übersehen, danke!
