### ISSUE TITLE
Kreuzen in 6. Runde

### ISSUE THREAD

**Issue by codebro634** [informatiCup/InformatiCup2021#14]
![test](https://user-images.githubusercontent.com/55958538/95213325-fc36e900-07ee-11eb-8a13-c7b763ed3a9d.png)

Angenommen wir befinden uns in der 6. Runde, die Schlangen hinterlassen also eine Lücke in der Spur und kreuzen sich im Punkt x. Wie gehen die Situationen 1 und 2 aus? Bzw. wer überlebt die Situationen?

**Comment by Top-Ranger** [comment]
Grundsätzlich gilt https://github.com/informatiCup/InformatiCup2021/issues/5. Da wir hier aber in Runde 6 sind entstehen bei Spielern mit Geschwindigkeit > 3 Löcher. Daher entsteht kein Zusammenstoß und beide überleben.

**Comment by codebro634** [comment]
Danke schonmal! In Situation 2 hat die grüne Schlange nur eine Geschwindigkeit von 2, hinterlässt also kein Loch. Das ist ja quasi eine Mischform aus Situation 1 und aus dem von dir verlinktem Issue 5. Wenn die Züge zunächst einmal ausgeführt werden dann kommt es zu einem Unfall, nämlich die rote Schlange ist dann durch die grüne Spur gelaufen. Sehe ich das so richtig, oder überlebt die rote Schlange doch?

**Comment by Top-Ranger** [comment]
Hier ist die selbe Situation: Die rote Schlange macht ein Loch, dadurch kommt es zu keinem Zusammenstoß.

**Comment by codebro634** [comment]
Ok jetzt habe ich es verstanden, danke!
