### ISSUE TITLE
Berechnung der Punktezahl

### ISSUE THREAD

**Issue by epistoteles** [informatiCup/InformatiCup2021#15]
In den Bewertungskriterien steht, dass ein Teil der Qualitaet des Agenten seine Punktzahl ist. Es wird jedoch nicht angegeben, wie sich diese Punktzahl berechnet.

Ist es zum Beispiel besser, wenn ein Agent aus 100 Spielen 50 Spiele gewinnt, 10 Spiele unentschieden abschliesst und 40 Spiele verliert oder nur 35 Spiele gewinnt, dafuer aber 65 Spiele unentschieden abschliesst? Macht es weiterhin einen Unterschied, ob man ein Spiel als zweiter, dritter oder gar letzter Spieler verliert?

Die Berechnung der Punktzahl beeinflusst massgeblich, wie sehr "agressive" Spielstrategien belohnt oder bestraft werden.

**Comment by Top-Ranger** [comment]
Die Bewertung findet ausschließlich nach der Abgabe statt. Vorherige Spiele während der Bearbeitungszeit werden nicht gewertet. Ihr könnt also problemlos vorher experimentieren :)

Für die Bewertung im Bereich "Qualität der Lösung" ist vor allem die Anzahl an gewonnenen Spielen entscheidend. Bitte beachtet, dass dies nur eines der Bewertungskriterien ist.
