### ISSUE TITLE
Gleichzeitiges ausscheiden der letzten 2 Spieler

### ISSUE THREAD

**Issue by Brutaline** [informatiCup/InformatiCup2021#18]
Was passiert, wenn die letzten beiden Spieler in der selben Runde ausscheiden? Zählt dies als Sieg für beide Spieler oder als Niederlage für beide? Oder gibt es eine andere Regel diesbezüglich die ich übersehe?

**Comment by Top-Ranger** [comment]
In dem Fall hat kein Spieler gewonnen.
