### ISSUE TITLE
429 Too Many Requests

### ISSUE THREAD

**Issue by DiddiZ** [informatiCup/InformatiCup2021#19]
Wie lange muss der Client warten, bevor er erneut eine Verbindung aufbauen darf, nachdem er einmal Error 429 erhalten hat?

Wenn mein Client 60s wartet und dann versucht, sich erneut zu verbinden, erhält er wieder einen Error 429. Dies wiederholt sich endlos über Stunden. 

Ausgehend von dem bereitgestellten PDF würde ich davon aussgehen, dass sobald das ursprüngliche Spiel beendet ist, die Verbindungsanfrage erfolgreich ist.

**Comment by Top-Ranger** [comment]
Der Client kann sich dann wieder mit dem Server verbinden, sobald das Spiel beendet ist, an dem der Client teilnimmt. Dabei müsst ihr beachten, dass das Spiel auch weiterlaufen kann, auch wenn euer Client keine Verbindung mehr zum Server hat. In dem Fall müsst ihr warten, bis das Spiel vorbei ist (dies ist leider nicht ersichtlich, wenn ihr nicht mehr mit dem Spiel verbunden seid).

Bitte beachtet, dass es etwas dauern kann, bis der erste Spielstatus übertragen wird. Solange auf den Start des Spiels gewartet wird werden keine Daten übertragen.

**Comment by DiddiZ** [comment]
Genau so dachte ich mir das. Allerdings sollte das nicht mehrere Stunden dauern.

z.B. haben wir gestern gegen 22:30 aus Versehen von zwei Client aus connected und dafür den Error 429 erhalten. Danach konnten wir über Stunden nicht mehr erfolgreich verbinden. Um halb 1 ging es nocht nicht, erst heute Morgen klappt es wieder.

Ausschnitt aus unserem Log:
```txt
2020-11-01 22:18:52 DEBUG: client < HTTP/1.1 429 Too Many Requests
2020-11-01 22:20:52 DEBUG: client < HTTP/1.1 429 Too Many Requests
2020-11-01 22:26:54 DEBUG: client < HTTP/1.1 429 Too Many Requests
2020-11-01 22:28:54 DEBUG: client < HTTP/1.1 429 Too Many Requests
2020-11-01 22:31:55 DEBUG: client < HTTP/1.1 429 Too Many Requests
2020-11-01 22:34:56 DEBUG: client < HTTP/1.1 429 Too Many Requests
2020-11-01 22:37:57 DEBUG: client < HTTP/1.1 429 Too Many Requests
2020-11-01 22:40:57 DEBUG: client < HTTP/1.1 429 Too Many Requests
2020-11-01 22:42:58 DEBUG: client < HTTP/1.1 429 Too Many Requests
2020-11-01 22:47:59 DEBUG: client < HTTP/1.1 429 Too Many Requests
2020-11-01 22:53:01 DEBUG: client < HTTP/1.1 429 Too Many Requests
2020-11-01 22:58:02 DEBUG: client < HTTP/1.1 429 Too Many Requests
2020-11-01 23:03:03 DEBUG: client < HTTP/1.1 429 Too Many Requests
2020-11-01 23:09:05 DEBUG: client < HTTP/1.1 429 Too Many Requests
2020-11-02 00:06:36 DEBUG: client < HTTP/1.1 429 Too Many Requests
2020-11-01 23:32:06 DEBUG: client < HTTP/1.1 429 Too Many Requests
2020-11-01 23:33:06 DEBUG: client < HTTP/1.1 429 Too Many Requests
```

Ich habe den Eindruck, das nicht erfolgreiche Verbindungsversuche dafür sorgen, dass der nächste Verbindungsversuch ebenfalls nicht erfolgreich ist. Es funktioniert erst wieder, wenn man die Verbindungsschleife beendet und einige Stunden wartet.

**Comment by Top-Ranger** [comment]
Ein erfolgloser Versuch verhindert keine weiteren Versuche. Wenn sich zwei verschiedene Clienten verbinden, dann bleibt der erste im Spiel  / in der Lobby (und kann das Spiel zu Ende spielen) und der zweite bekommt die 429-Meldung. So weit ich das nachvollziehen kann sind auch für alle Teilnehmer, die sich in dem Zeitraum mit der API verbunden haben, Spiele gestartet worden.

**Comment by DiddiZ** [comment]
MWE: 

```python
#!/usr/bin/env python3

import asyncio
import json
import os
import random
import websockets


async def connect_and_quit():
    url = os.environ["URL"]
    key = os.environ["KEY"]

    async with websockets.connect(f"{url}?key={key}"):
        print("Connected", flush=True)
    print("Disconnected", flush=True)


async def play():
    url = os.environ["URL"]
    key = os.environ["KEY"]

    print("Connecting", flush=True)
    try:
        async with websockets.connect(f"{url}?key={key}") as websocket:
            print("Waiting for initial state...", flush=True)
            while True:
                state_json = await websocket.recv()
                state = json.loads(state_json)
                print("<", state)
                own_player = state["players"][str(state["you"])]
                if not state["running"] or not own_player["active"]:
                    break
                valid_actions = ["turn_left", "turn_right", "change_nothing"]
                if own_player["speed"] < 10:
                    valid_actions += ["speed_up"]
                if own_player["speed"] > 1:
                    valid_actions += ["slow_down"]
                action = random.choice(valid_actions)
                print(">", action)
                action_json = json.dumps({"action": action})
                await websocket.send(action_json)
    except websockets.exceptions.InvalidStatusCode as e:
        if e.status_code == 429:  # Server rejects us
            print("Server rejected connection", flush=True)

            # Sleep and try again
            await asyncio.sleep(60)
            await play()
        else:  # Other status code, not handled here
            raise


asyncio.get_event_loop().run_until_complete(connect_and_quit())
asyncio.get_event_loop().run_until_complete(play())
```

Und tatsächlich, das funktioniert wie erwartet. Dann liegt das Problem wohl auf unserer Seite. Auch wenn es sehr merkwürdig ist, dass es auch nach einem Restart des Docker-Containers nicht geklappt hat. Aber dann kann das hier zu.
