### ISSUE TITLE
Neue API: Serverzeit

### ISSUE THREAD

**Issue by Top-Ranger** [informatiCup/InformatiCup2021#20]
Wir haben eine neue API hinzugefügt: Unter https://msoll.de/spe_ed_time könnt ihr die aktuelle Server-Zeit (in UTC) als JSON abfragen. Für die Deadline ist die Serverzeit maßgeblich. Die Serverzeit an sich war bis jetzt und sollte auch in Zukunft sehr genau sein. Die Benutzung der API ist weder notwendig noch wird sie verlangt, soll euch aber beim Eliminieren von möglichen Problemen helfen. Ein API-Key wird für die neue Schnittstelle nicht benötigt. Bitte beachtet, dass es Verzögerungen durch langsame Internetverbindungen geben kann.

**Comment by Top-Ranger** [comment]
Die URL zur Serverzeit wird für die Docker-Lösung über die Umgebungsvariable ```TIME_URL``` übergeben. Die Benutzung ist komplett optional, und wir empfehlen bei der Nutzung trotzdem ein Fehlermanagement.

**Comment by Sohn123** [comment]
Steht immer eine Time API zur Verfügung oder kann ein Client auch ohne Time API aufgerufen werden und sollte diesen Fall handeln?

**Comment by Top-Ranger** [comment]
Wir werden euch immer über ```TIME_URL``` einen Endpunkt zur Verfügung stellen. Die Nutzung ist komplett optional - es entsteht kein Nachteil in der Wertung, wenn der Endpunkt nicht verwendet wird. Auch wenn dieser immer ein Datum zur Verfügung stellen sollte, so empfehlen wir doch im Sinne der defensiven Programmierung immer ein entsprechendes Fehlermanagement zu haben.
