### ISSUE TITLE
Kriterium fürs Ausscheiden eines Spielers

### ISSUE THREAD

**Issue by rynkk** [informatiCup/InformatiCup2021#21]
> "Dabei scheidet ein Spieler aus, sobald er einen anderen Spieler oder eine bereits vorhandene Spur berührt [...]"

Berührt Spieler1 Spieler2, wenn Spieler2 in den von Spieler1 im selben Zug erzeugten Schwanz fährt? Genaugenommen kreuzt Spieler1 Spieler2 dann ja nur indirekt.

Daraus ergibt sich ebenfalls die Frage, wie es sich verhält, wenn beide Spieler (einer von unten nach oben , einer von links nach rechts) im selben Zug über den selben Punkt fahren, gewinnt dann der Spieler der als erstes (Funktion aus Abstand und Geschwindigkeit) dagewesen wäre oder verlieren beide?

**Comment by merkrafter** [comment]
Es verlieren beide; siehe [hier](https://github.com/informatiCup/InformatiCup2021/issues/5)

**Comment by rynkk** [comment]
Danke sehr

**Comment by rynkk** [comment]
Danke Sehr
