### ISSUE TITLE
Wie lange bekommt man für einen Zug, also wie weit ist die Deadline entfernt

### ISSUE THREAD

**Issue by Fabioni** [informatiCup/InformatiCup2021#22]
Guten Tag,
mich würde mal interessieren wie viel Zeit ein Bot für einen Zug hat. Falls es nicht festgelegt ist, in welchen Dimensionen liegt das ganze denn? Sekunden, Millisekunden, etc.

Vielen Dank für die Antwort!

**Comment by Top-Ranger** [comment]
Moin,
ihr könnt euch grob an den Werten des Testservers unter wss://msoll.de/spe_ed orientieren. Bitte beachtet auch, dass die Referenzsysteme sich in der Leistungsfähigkeit von euren Systemen unterscheiden können (siehe https://github.com/informatiCup/InformatiCup2021/issues/11 )

**Comment by mzietlow** [comment]
Das Fehlen einer unteren Grenze sowohl von Antwortzeit als auch Leistungsfähigkeit der Referenzsysteme sorgt in der Entwicklung für größere Unsicherheit.

Können hier wirklich keine Zugeständnisse gemacht werden? 🙁

**Comment by Top-Ranger** [comment]
Die Unsicherheit ist Teil der Aufgabenstellung - eure Lösung sollte mit der Unsicherheit umgehen können.

Zudem möchte ich nochmal auf unsere neue Zeit-API verweisen, mit der ihr die (maßgebliche) Server-Zeit abfragen könnt: https://github.com/informatiCup/InformatiCup2021/issues/20

**Comment by GabrielBlaut** [comment]
Ändert sich die Deadline (Zeit für einen Zug)  über das Spiel hinweg? Im Beispielvideo brauchen die Bots am Anfang etwas länger und am Ende läuft es schnell. Oder wird die Zeit für einen Zug,  wenn in einem Spiel am Anfang festgelegt,  so bleiben?

**Comment by Top-Ranger** [comment]
Es gelten jeweils die Zeiten, die in einer Runde gesendet werden. Ihr könnt davon ausgehen, dass die Deadlines unabhängig voneinander festgelegt werden.
