### ISSUE TITLE
Was passiert, wenn zwei Spieler gleichzeitig auf dasselbe ein Feld ziehen?

### ISSUE THREAD

**Issue by jacob271** [informatiCup/InformatiCup2021#23]
Wenn ich das richtig interpretiert habe, müssten beide ausscheiden, da sie den jeweils anderen berühren. Liege ich damit richtig?

**Comment by Top-Ranger** [comment]
In dem Fall scheiden beide Spieler aus - siehe auch https://github.com/informatiCup/InformatiCup2021/issues/5

**Comment by jacob271** [comment]
Ok, danke!
