### ISSUE TITLE
Fehler in API Doku

### ISSUE THREAD

**Issue by pa-ssch** [informatiCup/InformatiCup2021#24]
In dem Beispiel JSON-Datensatz steht für die möglichen Werte der Cell-Liste "-1              gleichzeitig durch mehrere Spieler belegt".

Jedoch wird auch der Wert -1 gesetzt, wenn das Feld durch einen einzigen Spieler doppelt belegt ist, falls er mit sich selbst kollidiert (siehe Bild - Auszug aus dem vom Server erhaltenen JSON-Datensatz).

![image](https://user-images.githubusercontent.com/56266659/99070100-ef58a280-25af-11eb-8d82-c079294adca0.png)

**Comment by Top-Ranger** [comment]
Vielen Dank, da hätten wir tatsächlich etwas präziser sein können (z.B. "Mehrfach durch Spieler belegt").
