### ISSUE TITLE
Sind die Startpositionen immer spielbar und fair?

### ISSUE THREAD

**Issue by GabrielBlaut** [informatiCup/InformatiCup2021#25]
Garantiert der Spielserver, dass der Spieler nach der Startposition einen gültigen Spielzug ausführen kann? 

Folgendes Beispiel für eine unfaire Position:
Spieler 1 ist in der oberen rechten Ecke von dem Spielfeld und schaut nach rechts gegen die Wand. 
Spieler 2 hat eine Startposition unter ihm. 

Jede mögliche Aktion von Spieler 1 führt im nächsten Zug zu seinem Tod. 
Er ist von links und vorne von der Wand geblockt und von rechts von Spieler 2. 

Dieses Beispiel ist konstruiert und passiert sehr selten in einem großen Spielfeld. In einem kleinen Spielfeld könnte dies Relevanz haben.

**Comment by Top-Ranger** [comment]
Bei jeder Startbelegung wird darauf geachtet, dass jeder Spieler am Anfang Züge machen kann.

**Comment by GabrielBlaut** [comment]
Kann man daraus schließen, dass die Startbelegungen nicht gleichverteilt sind? Manche Startbelegungen kommen nie vor, sodass die Wahrscheinlichkeit der anderen erhöht wird.

**Comment by Top-Ranger** [comment]
Ja, einige Startbelegungen werden ausgeschlossen.
