### ISSUE TITLE
Soll die URL für die Serverzeit auch als Umgebungsvariable an den Docker-Container übergeben werden können?

### ISSUE THREAD

**Issue by jonashellmann** [informatiCup/InformatiCup2021#26]
In den Anforderungen steht, dass die Server-URL und der Key beim Start des Docker-Containers mittels dem Parameter `-e` als Umgebungsvariablen gesetzt werden.

Wenn wir auch die URL zur Abfrage der aktuellen Serverzeit (https://msoll.de/spe_ed_time) nutzen wollen, wird diese URL ebenfalls als Umgebungsvariable gesetzt oder sollte diese hart im Code bzw. im Dockerfile hinterlegt werden? Bisher steht in den Anforderungen nicht drin, dass beim Container-Start eine dritte Umgebungsvariable gesetzt wird.

**Comment by Top-Ranger** [comment]
Ja, das Problem haben wir leider bei der Erstellung der Serverzeit-Schnittstelle übersehen :sweat_smile:

Wir werden die URL über die Umgebungsvariable ```TIME_URL``` mit übergeben. Wir würden trotzdem empfehlen, auf ein gutes Fehlermanagement zu achten.

**Comment by jonashellmann** [comment]
Alles klar, vielen Dank für die Antwort! 👍🏻
