### ISSUE TITLE
Nur TimeOuts nach Verbindungsversuchen

### ISSUE THREAD

**Issue by MrDrache333** [informatiCup/InformatiCup2021#29]
Moin.
Wir nutzen Python3.8.2 und haben anfangs versucht, die API mittels des zur Verfügung gestellten Codes anzufragen und die JSON zu laden.
Die wird allerdings nach wenigen Sekunden mit:
```python
Waiting for initial state...
DEBUG:websockets.protocol:client - event = data_received(<4 bytes>)
DEBUG:websockets.protocol:client < Frame(fin=True, opcode=8, data=b'\x03\xe8', rsv1=False, rsv2=False, rsv3=False)
DEBUG:websockets.protocol:client ! timed out waiting for TCP close
DEBUG:websockets.protocol:client x closing TCP connection
DEBUG:websockets.protocol:client - event = connection_lost(None)
DEBUG:websockets.protocol:client - state = CLOSED
DEBUG:websockets.protocol:client x code = 1000, reason = [no reason]
Zeitüberschreitung bei Verbindungsaufbau!
code = 1000 (OK), no reason
```
Beendet

Selten kann eine Verbindung aufgebaut werden und dann wird auch eine Antwort unsererseits gesendet. Daraufhin erhalten wir jedoch wieder die gleiche Antwort wie bereits oben beschrieben.
Welche Ursachen könnte dies haben?

**Comment by Top-Ranger** [comment]
Moin,
leider können wir nicht das Debugging für euch übernehmen. Hier jedoch einige Hinweise, die euch helfen könnten:
1. Es kann vorkommen, dass der Server für kurze Zeit auf Grund von Wartungen manchmal nicht erreichbar ist. Hier würde ich empfehlen, einfach 5 Minuten zu warten und es dann noch einmal zu probieren. Wir können leider nur eine Verfügbarkeit von 99,9% garantieren.
2. Habt ihr probiert, euch mit der [Beispiellösung](https://github.com/informatiCup/InformatiCup2021/tree/master/docker_example) zu verbinden? Diese sollte problemlos funktionieren. Wenn auch da über längeren Zeitraum Probleme auftreten, dann würde ich den Fehler stark auf eurer Seite vermuten.
3. Es ist nicht möglich, ohne Zeitangabe hier irgendwelche Informationen nachzuschauen. Bitte hängt bei Serverproblemen immer Zeitangaben an (Beachtet auch eine mögliche Differenz zur [Serverzeit](https://msoll.de/spe_ed_time), auf einem System mit präziser Zeit sollte der Unterschied nicht ins Gewicht fallen)

**Comment by MrDrache333** [comment]
Hat sich erledigt. Verbindung wurde irrtümlicherweise durch eine verrutschte Codezeile beendet. Trotzdem Danke.
