### ISSUE TITLE
Verwendung des Informaticup Logos

### ISSUE THREAD

**Issue by pa-ssch** [informatiCup/InformatiCup2021#30]
Hallo,

dürfen wir (bezüglich des Urheberrechts) das Informaticup Logo in unseren Ausarbeitungen / auf unseren Seiten / Repos verwenden (ggfs. auch eine Abwandlung oder nur einen Auszug davon)?

**Comment by AlexPaar** [comment]
Da wo es sinnvoll ist dürft Ihr das InformatiCup-Logo verwenden. Es gibt dazu jetzt auch zwei entsprechende Bilddateien im Repo. Das Logo abzuändern oder zu entfremden ist wahrscheinlich keine gute Idee.
