### ISSUE TITLE
Wie soll die Abgabe unseres Projekts erfolgen?

### ISSUE THREAD

**Issue by jonashellmann** [informatiCup/InformatiCup2021#31]
Ich habe bisher noch keine Informationen darüber gefunden, wie die Abgabe erfolgen soll (z.B. ein Upload als zip-Datei o.ä.), sondern nur, dass der letzte mögliche Tag der Abgabe der 17. Januar 2021 ist.
Über genauere Angaben dazu würde ich mich sehr freuen. Vielen Dank im Voraus schon einmal!

**Comment by bitflipp** [comment]
Aus https://informaticup.github.io/competition/30-faq:

> In jeder Form, per Brief, auf Papier, mit CD, per E-Mail oder gerne als Download (wenn die Datei sehr groß ist). Der Quellcode sollte allerdings in elektronischer Form vorliegen, kompilierbar bzw. interpretierbar sein und das Programm korrekte Ergebnisse liefern.

**Comment by IcarusCoding** [comment]
An welche E-Mail-Adresse sollen wir unsere Abgabe schicken?

**Comment by Top-Ranger** [comment]
Schickt die Lösung an Ludger Porada.
