### ISSUE TITLE
Gibt es eine bestimmte Form, wie der Quelltext abgegeben werden muss? Muss ich ein git-Repository abgeben?

### ISSUE THREAD

**Issue by Top-Ranger** [informatiCup/InformatiCup2021#33]
Ein gesondertes Repository ist nicht erforderlich. Auch eine Versionshistorie wird nicht erwartet. Es sollte allerdings der gesamte  relevante Quelltext in der Abgabe enthalten sein: Beachtet, dass das Image (allein) mit einem Aufruf an `docker build` gebaut werden können muss (s. Aufgabenstellung unter "Bewertung").

Siehe auch unser [FAQ](https://informaticup.github.io/competition/30-faq#wie-k%C3%B6nnen-wir-eine-l%C3%B6sung-einreichen)

**Comment by pa-ssch** [comment]
> Beachtet, dass das Image (allein) mit einem Aufruf an `docker build` gebaut werden können muss (s. Aufgabenstellung unter "Bewertung").

Da für den Aufruf an `docker build` die offizielle Referenz (`docker build [OPTIONS] PATH | URL | -`) in den Bewertungskriterien angegeben ist, ist meine Annahme, dass dieser eine Aufruf beliebige Parameter enthalten darf (z.b. der Pfad zum DockerFile, die URL zu dem Github Repository, der Build-Kontext über PATH, ...) - unter der Voraussetzung, dass dies dokumentiert ist.

Ist diese Annahme korrekt?



EDIT: Ich habe gerade in dem docker example gesehen, dass dort auch `OPTIONS` verwendet werden. Ich lasse meinen Kommentar trotzdem stehen, falls auch bei anderen die Frage aufkommt.

**Comment by bitflipp** [comment]
Ich bestätige, dass dokumentierte `docker build`-Parameter zulässig sind.
