### ISSUE TITLE
Was determiniert den Spielsieg? 

### ISSUE THREAD

**Issue by ddanhofer** [informatiCup/InformatiCup2021#34]
Ist es, um den ersten Platz in einem Spiel, d. h. einer Runde zu gewinnen, lediglich erforderlich als letzer am Leben zu bleiben oder spielt die Anzahl der "überstrichenen" Felder oder die erzielte "Körperlänge" ebenfalls eine Rolle?

**Comment by Top-Ranger** [comment]
Es ist nur entscheidend, ob / wer am Ende nicht ausscheidet

Siehe auch https://github.com/informatiCup/InformatiCup2021/issues/15
