### ISSUE TITLE
Sendezeit

### ISSUE THREAD

**Issue by luk-ha** [informatiCup/InformatiCup2021#35]
Gibt es einen Rahmen in dem sich die Zeit bewegen wird, die für das Versenden der Response benötigt wird? Von uns kann ja nicht geprüft werden, wann die Nachricht am Server ankommt. (Und das hängt ja unter anderem davon ab wie die Verbindung zwischen Client und Server aussieht.)

**Comment by Top-Ranger** [comment]
Eure Lösung muss mit der Unsicherheit umgehen können - ihr könnt den bekannten Endpoint gerne zum Testen verwenden.

Für die Bewertung solltet Ihr von einer normalen Internetverbindung ausgehen - wir werden keine Maßnahmen für zusätzliche Verzögerung einbauen, aber auch keine besonderen Beschleunigungen.
