### ISSUE TITLE
Hohe Latenz der Time API

### ISSUE THREAD

**Issue by rgwohlbold** [informatiCup/InformatiCup2021#36]
Seit gestern Abend antwortet die Time API deutlich langsamer, oft sogar über einer Sekunde. Das Problem tritt weiterhin auf. Ich habe unser Logging angepasst, sodass es zeigt, wie lange die API braucht. Auf der API lassen sich kaum noch richtige Spiele spielen, denn entweder stirbt unser Spieler oder die anderen Spieler, ohne dass sich Spuren kreuzen oder Spieler das Feld verlassen. Ich habe die beispielhafte Log-Nachrichten angehangen (unser HTTP client verwendet einen Timeout von 1s für die API).

Vielen Dank und viele Grüße,
Richard

-- LOG (Spiele durch Absätze getrennt)
2021/01/12 12:48:01 time api took 1.000249295s
2021/01/12 12:48:08 time api took 1.00016425s
2021/01/12 12:48:16 time api took 24.827832ms
2021/01/12 12:48:22 time api took 5.989834ms
2021/01/12 12:48:35 time api took 5.334849ms
2021/01/12 12:48:45 time api took 7.854876ms
2021/01/12 12:48:56 time api took 5.19368ms
2021/01/12 12:49:09 time api took 10.508569ms
2021/01/12 12:49:17 time api took 5.386409ms
2021/01/12 12:49:23 time api took 5.916717ms
2021/01/12 12:49:32 time api took 6.605539ms
2021/01/12 12:49:40 time api took 5.523025ms
2021/01/12 12:49:46 time api took 5.294932ms
2021/01/12 12:49:57 time api took 7.195379ms
2021/01/12 12:50:08 time api took 5.59691ms
2021/01/12 12:50:19 time api took 5.419777ms
2021/01/12 12:50:25 time api took 5.20932ms
2021/01/12 12:50:35 time api took 5.627138ms
2021/01/12 12:50:48 time api took 7.320601ms
2021/01/12 12:50:55 time api took 5.89549ms
2021/01/12 12:51:03 time api took 5.113487ms
2021/01/12 12:51:11 time api took 5.678592ms
2021/01/12 12:51:23 time api took 6.22052ms
2021/01/12 12:51:29 time api took 5.397028ms
2021/01/12 12:51:38 time api took 6.429176ms
2021/01/12 12:51:46 time api took 6.599128ms
2021/01/12 12:51:58 time api took 5.4638ms
2021/01/12 12:52:04 time api took 5.609186ms
2021/01/12 12:52:13 time api took 5.428113ms
2021/01/12 12:52:20 time api took 5.179794ms
2021/01/12 12:52:27 time api took 8.056841ms
2021/01/12 12:52:34 time api took 11.501981ms
2021/01/12 12:52:40 time api took 12.4168ms
2021/01/12 12:52:48 time api took 5.833985ms
2021/01/12 12:52:56 time api took 5.625228ms
2021/01/12 12:53:02 time api took 12.561608ms
2021/01/12 12:53:08 time api took 6.280089ms
2021/01/12 12:53:18 time api took 5.863361ms
2021/01/12 12:53:27 time api took 5.169668ms
2021/01/12 12:53:34 time api took 8.029728ms
2021/01/12 12:53:40 time api took 5.283242ms
2021/01/12 12:53:46 time api took 9.317617ms
2021/01/12 12:53:52 time api took 5.68861ms
2021/01/12 12:54:00 time api took 6.091337ms
2021/01/12 12:54:06 time api took 5.28367ms
2021/01/12 12:54:19 time api took 5.409503ms
2021/01/12 12:54:25 time api took 6.030893ms
2021/01/12 12:54:31 time api took 5.752722ms
2021/01/12 12:54:39 time api took 6.938367ms
2021/01/12 12:54:45 time api took 5.448365ms
2021/01/12 12:54:58 time api took 5.161122ms
2021/01/12 12:55:04 time api took 5.663328ms
2021/01/12 12:55:11 time api took 10.579287ms
2021/01/12 12:55:22 time api took 5.856283ms
2021/01/12 12:55:34 time api took 5.544641ms
2021/01/12 12:55:47 time api took 5.711631ms
2021/01/12 12:55:56 time api took 5.696116ms
2021/01/12 12:56:04 time api took 6.603074ms
2021/01/12 12:56:10 time api took 5.331075ms
2021/01/12 12:56:21 time api took 5.357351ms
2021/01/12 12:56:31 time api took 5.292699ms
2021/01/12 12:56:39 time api took 5.675029ms
2021/01/12 12:56:50 time api took 5.717674ms
2021/01/12 12:57:03 time api took 5.842374ms
2021/01/12 12:57:12 time api took 6.073365ms
2021/01/12 12:57:19 time api took 5.341802ms
2021/01/12 12:57:29 time api took 5.788751ms
2021/01/12 12:57:38 time api took 5.658813ms
2021/01/12 12:57:45 time api took 6.650248ms
2021/01/12 12:57:58 time api took 6.434089ms
2021/01/12 12:58:06 time api took 6.012983ms
2021/01/12 12:58:15 time api took 5.876397ms
2021/01/12 12:58:25 time api took 5.250761ms
2021/01/12 12:58:33 time api took 5.443301ms
2021/01/12 12:58:43 time api took 6.357959ms
2021/01/12 12:58:52 time api took 7.013762ms
2021/01/12 12:58:58 time api took 6.78651ms
2021/01/12 12:59:07 time api took 7.948359ms
2021/01/12 12:59:15 time api took 5.88314ms
2021/01/12 12:59:27 time api took 5.636215ms
2021/01/12 12:59:35 time api took 5.826687ms
2021/01/12 12:59:41 time api took 5.27148ms
2021/01/12 12:59:48 time api took 5.719046ms
2021/01/12 12:59:55 time api took 6.384852ms
2021/01/12 13:00:02 time api took 10.8983ms
2021/01/12 13:00:14 time api took 5.909427ms
2021/01/12 13:00:20 time api took 6.456303ms
2021/01/12 13:00:30 time api took 12.202216ms
2021/01/12 13:00:40 time api took 5.641535ms
2021/01/12 13:00:53 time api took 5.613735ms
2021/01/12 13:01:05 time api took 7.335223ms
2021/01/12 13:01:16 time api took 5.594709ms
2021/01/12 13:01:29 time api took 5.147198ms
2021/01/12 13:01:36 time api took 6.470165ms
2021/01/12 13:01:49 time api took 5.578262ms
2021/01/12 13:02:01 time api took 6.54392ms
2021/01/12 13:02:07 time api took 33.887441ms
2021/01/12 13:02:16 time api took 7.999281ms
2021/01/12 13:02:29 time api took 8.762147ms
2021/01/12 13:02:40 time api took 5.581281ms
2021/01/12 13:02:48 time api took 5.860946ms
2021/01/12 13:02:55 time api took 6.844756ms
2021/01/12 13:03:02 time api took 6.016808ms
2021/01/12 13:03:13 time api took 5.414266ms
2021/01/12 13:03:26 time api took 6.60598ms
2021/01/12 13:03:33 time api took 7.494225ms
2021/01/12 13:03:45 time api took 5.426171ms
2021/01/12 13:03:55 time api took 5.562551ms
2021/01/12 13:04:06 time api took 5.218291ms
2021/01/12 13:04:12 time api took 5.023034ms
2021/01/12 13:04:23 time api took 5.422694ms
2021/01/12 13:04:31 time api took 5.079645ms
2021/01/12 13:04:37 time api took 11.551403ms
2021/01/12 13:04:49 time api took 8.444468ms
2021/01/12 13:04:55 time api took 5.524104ms
2021/01/12 13:05:04 time api took 5.362817ms
2021/01/12 13:05:10 time api took 11.223894ms
2021/01/12 13:05:23 time api took 5.837737ms
2021/01/12 13:05:29 time api took 5.040075ms
2021/01/12 13:05:42 time api took 8.286857ms
2021/01/12 13:05:54 time api took 5.721451ms
2021/01/12 13:06:04 time api took 5.636461ms
2021/01/12 13:06:10 time api took 7.2278ms
2021/01/12 13:06:16 time api took 4.928137ms
2021/01/12 13:06:24 time api took 5.689576ms
2021/01/12 13:06:36 time api took 6.353128ms
2021/01/12 13:06:45 time api took 5.454151ms
2021/01/12 13:06:56 time api took 7.404936ms
2021/01/12 13:07:02 time api took 6.897208ms
2021/01/12 13:07:14 time api took 6.707001ms
2021/01/12 13:07:21 time api took 7.82244ms
2021/01/12 13:07:31 time api took 4.989836ms
2021/01/12 13:07:41 time api took 5.479316ms
2021/01/12 13:07:52 time api took 5.221964ms
2021/01/12 13:07:59 time api took 5.548777ms
2021/01/12 13:08:06 time api took 5.086627ms
2021/01/12 13:08:17 time api took 5.272272ms
2021/01/12 13:08:28 time api took 7.582584ms
2021/01/12 13:08:34 time api took 5.551989ms
2021/01/12 13:08:41 time api took 5.766958ms
2021/01/12 13:08:50 time api took 5.099657ms
2021/01/12 13:09:00 time api took 8.5115ms
2021/01/12 13:09:11 time api took 5.379848ms
2021/01/12 13:09:23 time api took 26.214542ms
2021/01/12 13:09:32 time api took 5.379069ms
2021/01/12 13:09:40 time api took 5.66656ms
2021/01/12 13:09:46 time api took 5.29545ms
2021/01/12 13:09:54 time api took 5.20293ms
2021/01/12 13:10:00 time api took 5.912751ms
2021/01/12 13:10:07 time api took 5.836984ms
2021/01/12 13:10:13 time api took 5.114134ms
2021/01/12 13:10:23 time api took 5.340429ms
2021/01/12 13:10:34 time api took 5.357679ms
2021/01/12 13:10:40 time api took 5.006072ms
2021/01/12 13:10:52 time api took 5.593535ms
2021/01/12 13:11:05 time api took 5.424397ms
2021/01/12 13:11:17 time api took 5.494128ms
2021/01/12 13:11:28 time api took 6.586465ms
2021/01/12 13:11:35 time api took 5.247138ms
2021/01/12 13:11:48 time api took 5.697413ms
2021/01/12 13:11:56 time api took 6.07533ms
2021/01/12 13:12:08 time api took 5.823687ms
2021/01/12 13:12:21 time api took 188.930834ms
2021/01/12 13:12:27 time api took 188.487341ms
2021/01/12 13:12:35 time api took 189.128578ms
2021/01/12 13:12:45 time api took 544.349503ms
2021/01/12 13:12:56 time api took 1.000190893s

2021/01/12 13:13:06 time api took 1.000346674s
2021/01/12 13:13:13 time api took 976.46478ms
2021/01/12 13:13:24 time api took 1.000152743s
2021/01/12 13:13:31 time api took 1.000135561s
2021/01/12 13:13:45 time api took 1.000076267s
2021/01/12 13:13:55 time api took 1.000182294s
2021/01/12 13:14:00 time api took 1.000064275s
2021/01/12 13:14:09 time api took 1.000150051s

2021/01/12 13:16:55 time api took 25.372137ms
2021/01/12 13:17:02 time api took 7.062379ms
2021/01/12 13:17:06 time api took 8.367349ms
2021/01/12 13:17:13 time api took 5.502299ms
2021/01/12 13:17:26 time api took 5.819069ms
2021/01/12 13:17:39 time api took 192.357495ms
2021/01/12 13:17:44 time api took 447.696957ms
2021/01/12 13:17:52 time api took 189.295845ms
2021/01/12 13:18:01 time api took 189.557778ms
2021/01/12 13:18:09 time api took 189.150367ms
2021/01/12 13:18:18 time api took 758.285081ms

**Comment by Fabioni** [comment]
Das kann ich bestätigen. Bei uns läuft seit gestern garnichts mehr, und das obwohl wir die Nutzung der time_url sogar wieder rausgenommen haben, wegen der hohen Latenz. In manchen Spielen setzt uns der Server einfach ohne Grund auf verloren nach ein paar Runden, weil er scheinbar unsere gesendete Aktion nicht mitbekommt.

**Comment by Top-Ranger** [comment]
Leider kann ich im Moment das Problem weder nachvollziehen noch reproduzieren. Im Moment scheint der Server für mich zu gehen. Ich behalte aber ein Auge auf dem Server, ob weitere Probleme auftreten. Ich würde mich freuen, falls ihr hier Status geben könntet.

**Comment by Fabioni** [comment]
wie hier und auch in #38 geschrieben treten viele plötzliche Tote auf. Könnte das daran liegen, dass euer Server intern auch die time_url anfrägt und es dabei dann eben auch zu diesen großen Verzögerungen kommt machmal?

**Comment by rgwohlbold** [comment]
Wir werden diese Nacht auf der API testen und uns morgen melden, falls weiterhin Probleme auftreten 👍

**Comment by rgwohlbold** [comment]
Heute Nacht war mit der Time API alles im Rahmen. Es sind öfters Gegner durch TImeouts gestorben, das ist bei uns jedoch nicht aufgetreten.

**Comment by rgwohlbold** [comment]
Das Problem ist nicht weiter aufgetreten, ich schließe das Issue deshalb.
