### ISSUE TITLE
Kollision über 2 Spielzüge

### ISSUE THREAD

**Issue by cryptic23dj1** [informatiCup/InformatiCup2021#39]
Wir haben einen interessanten Fall der Kollision gefunden. Dabei ist das erste kollidierende Feld noch aus einem vorherigen Zug, anders als in #5. Die Kollision wird dennoch voll ausgeführt und beide sterben. Ist dies gewolltes Verhalten?
Danke schon mal.

![1](https://user-images.githubusercontent.com/21223593/104440996-5fc17700-5593-11eb-8202-b8c70a5f4c49.png)
![2](https://user-images.githubusercontent.com/21223593/104441006-6354fe00-5593-11eb-97fa-876921c3df61.png)
![3](https://user-images.githubusercontent.com/21223593/104441013-65b75800-5593-11eb-9dc3-01685e37f4d5.png)

**Comment by Top-Ranger** [comment]
Aus unserer Sicht ist es das selbe verhalten wie in https://github.com/informatiCup/InformatiCup2021/issues/5 (beide kollidieren) und damit gewollt.

**Comment by cryptic23dj1** [comment]
Alles klar, danke schön
