### ISSUE TITLE
Abgabeprozess

### ISSUE THREAD

**Issue by lkaesberg** [informatiCup/InformatiCup2021#40]
Da die Deadline immer näher kommt, haben wir uns gerade damit beschäftigt wie genau denn der Abgabeprozess aussieht. Allerdings haben wir keine E-Mail-Adresse / Verlinkung gefunden, wo wir unser Ergebnis hinschicken / hochladen können. Die einzige Möglichkeit, die uns einfiel, wäre es an ludger.porada@gi.de zu schicken. Liegen wir damit richtig?

**Comment by Top-Ranger** [comment]
Ja, damit liegt ihr richtig.
