### ISSUE TITLE
Können wir unser Projekt als .zip abgeben, damit der docker richtig gebaut werden kann?

### ISSUE THREAD

**Issue by Jessi96LM** [informatiCup/InformatiCup2021#41]

**Comment by Top-Ranger** [comment]
Ja, solange das ZIP eine Dockerfile enthält und das Projekt nur mit einem Aufruf von ```docker build``` gebaut werden kann.

**Comment by Jessi96LM** [comment]
da ich hier noch keine Vorerfahrung habe noch eine kurze Nachfrage:
kann ich davon ausgehen, dass die zip Datei vorher entpackt wird?

**Comment by Top-Ranger** [comment]
Ja, wir entpacken die ZIP-Datei (außer ihr wollt etwas anderes)
