### ISSUE TITLE
Websocket handshake declined

### ISSUE THREAD

**Issue by marlince** [informatiCup/InformatiCup2021#42]
Hallo, 

mit unserer momentanen Implementation wird leider der WS Handshake abgelehnt. 
Ist es notwendig eine SSL veschlüsselte Verbindung zu nutzen?

**Comment by Top-Ranger** [comment]
Bei dem Endpunkt aus der Aufgabenstellung handelt es sich um ```wss://msoll.de/spe_ed?key=KEY```, also eine Verbindung mit dem Schema **wss:**, was für **WebSocket Protocol over TLS** steht. Folglich muss eine TLS-Verschlüsselte Verbindung benutzt werden.

Weitere Informationen findet Ihr in [RFC6455](https://tools.ietf.org/html/rfc6455).
