### ISSUE TITLE
Docker-File Java

### ISSUE THREAD

**Issue by YellowPhoenix18** [informatiCup/InformatiCup2021#43]
Guten Tag,
wir sind noch Neulinge im Umgang mit Docker, haben es aber soweit hinbekommen, dass unser Docker-Image gebaut wird und funktioniert.

Nun stellst sich aber die Frage, ob die Dockerfile direkt auf dem geklonten Repository ausgeführt wird. In diesem Falle müsste dann ja z.B. bei Java das Programm kompiliert werden oder reicht es, wenn wir in unserer Dockerfile auf eine jar-File im gebauten Ordner verweisen.

Vielen Dank bereits im voraus.

**Comment by Top-Ranger** [comment]
Mit Hilfe der Dockerfile soll ein Image erzeugt werden, welches auf den Referenzsystem läuft. Wenn ihr dafür eine .jar verwenden wollt ist das in Ordnung, beachtet bitte
1. Wir werden diese .jar nicht bauen, ihr müsst sie also mit ausliefern
2. Die .jar muss auf dem Referenzsystem laufen. Ihr dürft z.B. keine Abhängigkeiten zu etwas auf eurem System haben
3. Es sollte für uns möglich sein, die .jar zu bauen
