### ISSUE TITLE
Initialisierungs-Zeit

### ISSUE THREAD

**Issue by svenlr** [informatiCup/InformatiCup2021#44]
Unsere Lösung braucht initial auf langsamer Hardware schätzungsweise bis zu einer Minute, um einen Cache zu initialisieren.
Dies passiert natürlich, bevor eine Verbindung aufgebaut wird, um am Spiel teilzunehmen.
Ist das ein Problem?
Gibt es ein RAM-Limit pro Container?

**Comment by Top-Ranger** [comment]
Zur Frage 1: Es ist genau so ein Problem wie beim momentanen Server. Allerdings wäre es sinnvoll, dies irgendwo (Ausarbeitung, README) zu erwähnen, sonst könnte man beim Testen davon ausgehen, dass die Lösung nicht funktioniert.

Zur Frage 2: Es gibt kein hartes RAM-Limit, allerdings werden die Lösungen auf normalen (virtuellen) Computern getestet und sollten da auch lauffähig sein.
