### ISSUE TITLE
Was passiert, wenn zwei Spieler einen Punkt kreuzen, aber sich beide aufgrund deren Geschwindigkeit über den punkt hinaus bewegen würden?

### ISSUE THREAD

**Issue by pa-ssch** [informatiCup/InformatiCup2021#5]
Z. B. wenn bei diesem Bild beide Spieler Speed = 2 haben. 

![image](https://user-images.githubusercontent.com/56266659/94735916-bcde4780-036b-11eb-9ff6-0faafd059535.png)

Den Fall mit Rot-Speed = 1 & Grün-Sped = 2 konnte ich schon testen: Hier gewinnt Grün den Zweikampf.

**Comment by Top-Ranger** [comment]
Dann wird der Spielzug von allen komplett ausgeführt (also alle Felder entsprechend der Geschwindigkeit besetzt). Sollte es (wie hier) zu einem Unfall kommen, so scheiden alle daran beteiligten Spieler entsprechend aus.

**Comment by Top-Ranger** [comment]
> Den Fall mit Rot-Speed = 1 & Grün-Sped = 2 konnte ich schon testen: Hier gewinnt Grün den Zweikampf.

Das kann nicht sein, in diesem Fall sollten beide Spieler ausscheiden (habe das gerade auch nochmal nachgestellt).

**Comment by pa-ssch** [comment]
> > Den Fall mit Rot-Speed = 1 & Grün-Sped = 2 konnte ich schon testen: Hier gewinnt Grün den Zweikampf.
> 
> Das kann nicht sein, in diesem Fall sollten beide Spieler ausscheiden (habe das gerade auch nochmal nachgestellt).

Das habe ich gerade auch noch einmal geprüft, Sie haben recht. Ich bin davon ausgegangen, dass der Kopf von ausgeschiedenen Spielern schwarz ist, jedoch ist nur die Schnittstelle schwarz. Danke für die Info, bei einem Spiel mit 2 Spielern war mir nicht ganz ersichtlich, dass hier ein unentschieden entstanden ist.
