### ISSUE TITLE
GitHub Codespaces Access

### ISSUE THREAD

**Issue by pa-ssch** [informatiCup/InformatiCup2021#52]
Thank you @jonico !

**Comment by jonico** [comment]
Hast du https://github.com/features/codespaces/signup ausgefüllt?

**Comment by pa-ssch** [comment]
Jap

![image](https://user-images.githubusercontent.com/56266659/115888130-db647700-a452-11eb-8b9c-38b5a67c70de.png)

**Comment by pa-ssch** [comment]
Vielen Dank ❤️ !
