### ISSUE TITLE
GitHub Codespaces Access (Team Chillow)

### ISSUE THREAD

**Issue by jonashellmann** [informatiCup/InformatiCup2021#53]
@jonico Es wäre super, wenn wir von Team Chillow der Uni Oldenburg (@Florian3007 & @jonashellmann) Zugriff auf Github Codespaces bekommen könnten. Vielen Dank! 😄

**Comment by jonico** [comment]
Habt ihr https://github.com/features/codespaces/signup ausgefüllt?

**Comment by jonashellmann** [comment]
@jonico Ja, wir haben uns dort angemeldet
![grafik](https://user-images.githubusercontent.com/15215648/115896954-f242a380-a429-11eb-9893-5ae3a8418bc3.png)

**Comment by jonashellmann** [comment]
Besten Dank für das Freischalten des Zugriffs!
