### ISSUE TITLE
GitHub Codespaces Access: Team Jumpstart

### ISSUE THREAD

**Issue by ManuelPozor** [informatiCup/InformatiCup2021#57]
@jonico Wir würden uns auch über Zugang zu den Codespaces freuen!
Team Jumpstart (@DiddiZ @GregorKobsik @ManuelPozor)

**Comment by jonico** [comment]
Habt ihr alle schon die beta-terms ausgefüllt?

**Comment by ManuelPozor** [comment]
Ja, wir sind auf der waitlist.

**Comment by DiddiZ** [comment]
@jonico Thanks :)
