### ISSUE TITLE
Protokollverletzung im Beispielvideo

### ISSUE THREAD

**Issue by epistoteles** [informatiCup/InformatiCup2021#6]
Im Beispielvideo sieht man, wie der gelbe Agent direkt nach seiner ersten Rechtskurve einen Sprung mit einer Luecke macht, der bei Geschwindigkeit 3 auftritt. Da er zuvor keine Spruenge gemacht hat, ist das nur moeglich, wenn er gleichzeitig nach rechts dreht und beschleunigt. Es ist jedoch nach Anleitung verboten "mehrere Befehle innerhalb einer Spielrunde zu senden".

Gibt es hier einen Denkfehler?

**Comment by pa-ssch** [comment]
Runde 1: speed up (speed=2)
Runde 2: speed up (speed=3)
Runde 3: change nothing
Runde 4: change nothing
Runde 5: change nothing
Runde 6: turn right (und erster Sprung, weil 6 % 6 == 0. Nächster Sprung wieder in Runde 12, wenn Speed weiterhin >= 3)

**Comment by epistoteles** [comment]
Danke, Denkfehler gefunden :+1:
