### ISSUE TITLE
Code-Wiederverwendung

### ISSUE THREAD

**Issue by epistoteles** [informatiCup/InformatiCup2021#7]
In den FAQ steht, dass jede kostenlos verfügbare Bibliothek verwendet werden darf. Gilt das selbe fuer allen anderen kostenlos verfuegbaren Code, etwa aus oeffentlichen GitHub-Repositorys oder Implementierungen von Forschungsarbeiten?

**Comment by AlexPaar** [comment]
Sie dürfen Ihre Lösung auf jeder kostenlos verfügbaren Software aufbauen oder damit ermöglichen. Nennen Sie aber korrekt und vollständig die Autoren dieser Software und beachten Sie mögliche Lizenzbedingungen. In Ihrer Ausarbeitung sollte dann noch deutlich werden, was _Ihre_ Meriten einer funktionierenden Lösung sind und an welchen Stellen Sie schon vorher vorhandene Funktionalität verwenden.
