### ISSUE TITLE
Suggestion: Publish pre-built Docker container in the GitHub Container Registry for this organization

### ISSUE THREAD

**Issue by jonico** [informatiCup/InformatiCup2021#8]
@Top-Ranger: See https://docs.github.com/en/free-pro-team@latest/packages/getting-started-with-github-container-registry/about-github-container-registry and tell me if you encounter any issues

**Comment by Top-Ranger** [comment]
Now available at https://github.com/informatiCup/InformatiCup2021/packages/424833

**Comment by jonico** [comment]
@Top-Ranger: thank you, I did copy the docker image to the[ new GitHub Container registry](https://github.com/orgs/informatiCup/packages/container/package/icup2021_example), so that one can also pull it without GitHub credentials

```bash
docker pull ghcr.io/informaticup/icup2021_example:0.1
```
