### ISSUE TITLE
Ist das Pesudonym für den selben API-Key während der Evaluation der Einsendungen immer identisch?

### ISSUE THREAD

**Issue by epistoteles** [informatiCup/InformatiCup2021#9]
In der Aufgabenstellung steht, dass sich das Pseudonym "regelmäßig ändert". Sind die Zeiträume dazwischen so groß, dass sich das Pseudonym im Laufe der Evaluation nicht ändert? 

Hiermit ließen sich im Laufe der Spiele Schwachstellen in der Spielstrategie eines anderen Spielers feststellen und voraussagen.

**Comment by Epistoteles** [comment]
Hiermit ließen sich im Laufe der Spiele Schwachstellen in der Spielstrategie eines anderen Spielers feststellen und voraussagen.

**Comment by Top-Ranger** [comment]
Über den Zeitraum der Änderung sollte keine Annahme gemacht werden. Ich möchte auch darauf hinweisen, dass das Pseudonym nur am Ende des Spiels (bei "running": false) verfügbar ist - wie in der Aufgabe beschrieben.
